CREATE TABLE
	SOSAUSER ( id NUMBER(10) PRIMARY KEY,
	email VARCHAR2(255) NOT NULL CHECK(LENGTH(email)>1),
	password VARCHAR2(255) NOT NULL CHECK(LENGTH(password) > 1),
	admin NUMBER(10),
	wolf NUMBER(10) );

CREATE SEQUENCE SOSAUSER_seq
START WITH
1 INCREMENT BY 1;

CREATE OR REPLACE
TRIGGER SOSAUSER_seq_trigger BEFORE INSERT
	ON
	SOSAUSER FOR EACH ROW
BEGIN
	SELECT
		SOSAUSER_seq.nextval INTO
			:NEW.id
		FROM
			dual;
END;

CREATE OR REPLACE
PROCEDURE create_SOSAUSER(c_email IN VARCHAR2, c_password IN VARCHAR2, u_id OUT NUMBER) IS
BEGIN
INSERT
	INTO
		SOSAUSER (id, email, PASSWORD, admin, wolf);
	VALUES (SOSAUSER_seq.nextval, c_email, c_password, 0, 0);
u_id := SOSAUSER_seq.currval;

INSERT
	INTO
		SOSAUSERINFO (id);
	VALUES (SOSAUSER_seq.nextval);

END;
